import sys
import socket
import json
import numpy as np
import time
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(BASE_DIR))

from src.detection.hybrid_detector import HybridDetector
from src.core.behavior_engine import BehaviorEngine
from src.network.sniffer import PacketSniffer
from src.security.blacklist_manager import BlacklistManager
from src.security.unblock_manager import UnblockManager
from src.monitoring.security_logger import SecurityLogger
from src.ips.firewall import FirewallManager
from src.explainability.decision_explainer import explain_attack

from src.training.dataset_builder import save_sample
from src.training.training_scheduler import check_retraining


WHITELIST = [
    "127.",
    "192.168.",
    "10.",
    "172."
]


NETWORK_INTERFACE = "en0"


def get_local_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    try:
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    finally:
        s.close()

    return ip


LOCAL_IP = get_local_ip()


config_path = BASE_DIR / "configs" / "model_config.json"

with open(config_path) as f:
    config = json.load(f)


detector = HybridDetector(
    config["supervised_model_path"],
    config["unsupervised_model_path"],
    config
)

behavior_engine = BehaviorEngine()
firewall = FirewallManager()

blacklist = BlacklistManager(
    BASE_DIR / "logs" / "blacklist.txt"
)

unblock_manager = UnblockManager(
    firewall,
    blacklist,
    duration=300
)

security_logger = SecurityLogger()


print("\n🛡 AI-IPS LIVE PROTECTION STARTED")
print(f"📡 Monitoring Network Traffic on {LOCAL_IP}")
print(f"[AUTO] Using interface: {NETWORK_INTERFACE}\n")


last_log_time = 0
recent_blocks = {}
last_training_check = time.time()


def handle_packet(features, src_ip, dst_ip, dst_port, tcp_flag):

    global last_log_time
    global last_training_check

    try:

        if features is None:
            return

        # ignore packets generated by this machine
        if src_ip == LOCAL_IP:
            return

        # only inspect inbound traffic
        if dst_ip != LOCAL_IP:
            return

        # ignore trusted networks
        if any(src_ip.startswith(w) for w in WHITELIST):
            return

        if blacklist.is_blacklisted(src_ip):
            return

        try:
            dst_port = int(dst_port)
        except:
            dst_port = 0

        tcp_flag = str(tcp_flag)

        # Behavior detection
        behavior = behavior_engine.analyze(src_ip, dst_port, tcp_flag)

        behavioral_risk = behavior.get("risk", 0.0)
        attack_type = behavior.get("attack_type", "NORMAL")

        # AI detection
        ai_risk = 0.0

        try:
            result = detector.detect(np.array([features]))
            ai_risk = result.get("final_threat_score", 0.0)
        except:
            pass

        final_risk = max(behavioral_risk, ai_risk)

        # If AI triggered but rule engine didn't classify
        if attack_type == "NORMAL" and ai_risk > 0.6:
            attack_type = "AI_ANOMALY"

        # Self learning
        try:
            save_sample(features, attack_type)
        except:
            pass

        if time.time() - last_training_check > 30:

            try:
                check_retraining()
            except:
                pass

            last_training_check = time.time()

        # Decision engine
        if final_risk >= 0.65:

            if src_ip in recent_blocks:
                return

            recent_blocks[src_ip] = time.time()

            explanation = explain_attack(features, attack_type)

            print(f"[BLOCKED] {src_ip} — {attack_type}")

            if explanation:
                print("Reason:", explanation)

            firewall.block_ip(src_ip)
            blacklist.add_ip(src_ip)
            unblock_manager.block_with_timer(src_ip)

            security_logger.log_event(
                "BLOCKED",
                src_ip,
                "HIGH",
                attack_type
            )

        elif final_risk >= 0.40:

            now = time.time()

            if now - last_log_time > 1:
                print(f"[WARNING] {src_ip} — {attack_type}")
                last_log_time = now

            security_logger.log_event(
                "WARNING",
                src_ip,
                "MEDIUM",
                attack_type
            )

    except Exception as e:
        print("Packet processing error:", e)


def start_sniffer():

    print(f"[SNIFFER] Listening on interface: {NETWORK_INTERFACE}")

    while True:

        try:

            sniffer = PacketSniffer(interface=NETWORK_INTERFACE)
            sniffer.capture(handle_packet)

        except Exception:

            print("⚠ Sniffer crashed, restarting in 2s...")
            time.sleep(2)


if __name__ == "__main__":

    try:
        start_sniffer()

    except KeyboardInterrupt:

        print("\n🛑 AI-IPS stopped by user")
        print("Shutting down safely...")